version: '3'

services:
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    networks:
      - klicker-dev
    environment:
      API_ENDPOINT: http://localhost:4000/graphql
      API_ENDPOINT_WS: ws://localhost:4000/graphql
      CACHE_REDIS_ENABLED: true
      CACHE_REDIS_HOST: localhost
      S3_ROOT_DOMAIN: localhost
      S3_ROOT_URL: http://localhost:9000/images
      NEXT_PUBLIC_DISPLAY_AAI: 'false'
      NEXT_PUBLIC_HAPPYKIT_ANALYTICS_KEY: analytics_pub_1312f90ec4
      NEXT_PUBLIC_HAPPYKIT_FLAGS_ENV_KEY: flags_pub_development_313968481835942464
      NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID: G-0X8MP67657

  # redis instance to support session execution
  redis_exec:
    image: redis:5.0.9
    ports:
      - 6379:6379
    networks:
      - klicker-dev
    volumes:
      - /data

  # redis instance for page caching and rate limiting
  redis_cache:
    image: redis:5.0.9
    ports:
      - 6380:6379
    networks:
      - klicker-dev

  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: klicker
      MONGO_INITDB_ROOT_PASSWORD: klicker
    ports:
      - 27017:27017
    networks:
      - klicker-dev
    volumes:
      - /data/db

  # TODO: document having to create an images bucket and setting it to public
  minio:
    image: quay.io/minio/minio:RELEASE.2021-09-15T04-54-25Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:3000
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /data
    command: server /data --console-address ":9001"

  create_minio_buckets:
    image: minio/mc:RELEASE.2021-10-07T04-19-58Z
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    entrypoint: >
      /bin/sh -c '
      sleep 5;
      /usr/bin/mc config host add s3 http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} --api S3v4;
      [[ ! -z "`/usr/bin/mc ls s3 | grep images`" ]] || /usr/bin/mc mb s3/images;
      /usr/bin/mc policy set public s3/images;
      exit 0;
      '

  sendria:
    image: msztolcman/sendria:v2.2.2.0
    ports:
      - 1025:1025
      - 1080:1080

networks:
  klicker-dev:
    driver: bridge
